name: RustDesk RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download and run RustDesk client
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-host.exe" -OutFile "rustdesk-host.exe"
          Start-Process -FilePath "rustdesk-host.exe" -ArgumentList "--tray"
          Start-Sleep -Seconds 10
          Get-Content "$env:APPDATA\RustDesk\id" | ForEach-Object { "RustDesk ID: $_" }
          Get-Content "$env:APPDATA\RustDesk\passwd" | ForEach-Object { "RustDesk Password: $_" }
          Start-Sleep -Seconds 3600  # يبقى شغال ساعة
